export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_COURSES = 'UPDATE_COURSES';
export const UPDATE_COURSES_MYTRAINING ='UPDATE_COURSES_MYTRAINING';
export const UPDATE_EXAMS ='UPDATE_EXAMS';
export const UPDATE_ALL_CERTIFICATE ='UPDATE_ALL_CERTIFICATE';
export const UPDATE_CERTIFICATE ='UPDATE_CERTIFICATE';
export const UPDATE_TRAINING_CERTIFICATE_DETAIL ='UPDATE_TRAINING_CERTIFICATE_DETAIL';
export const UPDATE_CERTIFICATE_DETAIL ='UPDATE_CERTIFICATE_DETAIL';
export const UPDATE_MY_TRAINING ='UPDATE_MY_TRAINING';
export const FETCH_PETTY_CASH ='FETCH_PETTY_CASH';
export const FETCH_EMPLOYEES ='FETCH_EMPLOYEES';

