export const UPDATE_USER = 'UPDATE_USER';
export const FETCH_PETTY_CASH ='FETCH_PETTY_CASH';
export const FETCH_EMPLOYEES ='FETCH_EMPLOYEES';
export const FETCH_MANAGERS ='FETCH_MANAGERS';
export const FETCH_EMPLOYEE_BY_MANAGER ='FETCH_EMPLOYEE_BY_MANAGER';
export const FETCH_PETTY_CASH_BY_EMPLOYEE ='FETCH_PETTY_CASH_BY_EMPLOYEE';
export const FETCH_GENERAL_EMPLOYEE ='FETCH_GENERAL_EMPLOYEE';
export const FETCH_FINANCE_EMPLOYEE ='FETCH_FINANCE_EMPLOYEE';
export const FETCH_PETTY_CASH_APPROVE ='FETCH_PETTY_CASH_APPROVE';
export const FETCH_PETTY_CASH_RECEIVED ='FETCH_PETTY_CASH_RECEIVED';

